---
- name: Install Python and pip
  apt:
    name: [python3, python3-pip]
    state: present

- name: Install Flask
  pip:
    name: flask

- name: Clone the application code
  git:
    repo: https://github.com/X-culture24/yolo1.git
    dest: /var/www/ecommerce
