# Use the official MongoDB image
FROM mongo:5.0

# Optional: Copy a custom MongoDB configuration file
# COPY mongod.conf /etc/mongod.conf

# Expose the default MongoDB port
EXPOSE 27017

# Command to start MongoDB
CMD ["mongod"]
